### ISSUE TITLE
Offset example?

### ISSUE THREAD

**Issue by lunerenne** [bergant/airtabler#3]
Hi there,

Thanks for the package, it's awesome! I'm using it to pull some data from an Airtable that has more than 100 records, and it appears from your documentation that I need to make additional queries using an offset argument, and I think I'm interpreting correctly that offset = the record ID of the final record on the previous 100 records. However, that isn't working for me (I get "object not found") and I don't know what else to try. I was wondering if you would consider adding some clarifying information (or an example) to your documentation? I'd love to see how you go about fetching all records of something in a workflow when there are more than 100 records.

**Comment by syrnick** [comment]
The offset is returned as part of the API response. It is not the record ID. airtable.com/api has examples of the response.

**Comment by lunerenne** [comment]
I see the example offset there, but isn't that just for that specific example record? How can I find it for the specific record I need to offset by? Does it come through anywhere with airtabler or is there a way for me to find it on the airtable end?

**Comment by syrnick** [comment]
Apologies, that's a bug in documentation. The real offset would look like this:

```
"offset":"itrc0WsTbrR2mLh5t/rec5h71rI2OBxV3dW"
```

You need to take the value returned from the server and pass it back in the next request.

**Comment by syrnick** [comment]
Here's where javascript client handles the offset https://github.com/Airtable/airtable.js/blob/master/lib/query.js#L74

Here's ruby version: https://github.com/Airtable/airtable-ruby/blob/master/lib/airtable/table.rb#L16

**Comment by bergant** [comment]
This is a bug in R client. Missed the offset in the response...

**Comment by bergant** [comment]
Please, check the updated version. The example is now included in the readme (https://github.com/bergant/airtabler#using-page-size-and-offset)

**Comment by syrnick** [comment]
Very nice! Btw, airtable.js added "select(...).all()" method, to do this iteration under the hood and return all rows. https://github.com/Airtable/airtable.js/blob/master/CHANGELOG.md

**Comment by bergant** [comment]
@syrnick yes, this is very convenient. Maybe a `select_all` without page and offset parameters would be OK here...

**Comment by bergant** [comment]
Added `select_all` in new version.

**Comment by lunerenne** [comment]
Hey, select_all seems awesome! Thank you so much for the addition! However, I tried using select_all and got this error: "Error in rbind(deparse.level, ...) : 
  numbers of columns of arguments do not match" - any ideas?

**Comment by bergant** [comment]
Strange... looks like partial results from paging have different columns? Do you have any idea how to reproduce this error from some public airtable database?

**Comment by bergant** [comment]
Never mind... I found the reproducible example...
